version: '3.8'

services:
  gc-testing-app-g1gc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8089"
    networks:
      - test-network
    environment:
      - G1GC_PARAMS=-XX:+UseG1GC

  gc-testing-app-zgc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8089"
    networks:
      - test-network
    environment:
      - ZGC_PARAMS=-XX:+UseZGC

  newman:
    depends_on:
      - gc-testing-app-g1gc
      - gc-testing-app-zgc
    networks:
      - test-network
    volumes:
      - ./postman-collection:/etc/newman
    command: run /etc/newman/Testing.json --delay-request 1000 --reporter-json-export /etc/newman/results.json

networks:
  test-network:
    driver: bridge
    external: true
