version: '3.8'

services:
  gc-testing-app-g1gc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8089"
    networks:
      - test-network
    environment:
      - G1GC_PARAMS=-XX:+UseG1GC


networks:
  test-network:
    driver: bridge
    external: true
