name: Comparison of Garbage Collectors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "gc-testing-image"
      APP_PORT: 8080
      G1GC_PARAMS: "-XX:+UseG1GC"
      ZGC_PARAMS: "-XX:+UseZGC"

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # Set up Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      # Make Gradlew executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build the JAR file
      - name: Build the JAR file
        run: ./gradlew build

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      # Set up Docker and Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      #Install docker compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Run Docker Compose
      - name: Run Docker Compose
        run: docker-compose up -d

      # Run Postman tests with Newman for G1GC
      - name: Run Postman Tests (G1GC)
        run: |
          docker exec -t newman newman run /etc/newman/Testing.postman_collection.json --reporter-json-export /etc/newman/g1gc_results.json
        id: g1gc-test

      # Run Postman tests with Newman for ZGC
      - name: Run Postman Tests (ZGC)
        run: |
          docker exec -t newman newman run /etc/newman/Testing.postman_collection.json --reporter-json-export /etc/newman/zgc_results.json
        id: zgc-test

      # Stop and remove containers using Docker Compose
      - name: Stop and Remove Containers
        run: |
          docker-compose down

      # Publish Test Results
      - name: Publish Test Results to GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          name: gc-comparison-results
          path: results/
