name: Comparison of Garbage Collectors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      IMAGE_NAME: "gc-testing-image"
      APP_PORT: 8089
      G1GC_PARAMS: "-XX:+UseG1GC"
      ZGC_PARAMS: "-XX:+UseZGC"

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Create results directory dynamically
      - name: Create Results Directory
        run: mkdir -p results

      # Set up Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # Set up Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      # Make Gradlew executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build the JAR file
      - name: Build the JAR file
        run: ./gradlew build

      # Create Docker network
      - name: Create Network
        run: docker network create test-network

      # Build and start the G1GC container
      - name: Run G1GC Container
        run: |
          docker compose up -d gc-testing-app-g1gc

      # Run Postman tests for G1GC
      - name: Run Postman Tests (G1GC)
        run: |
          docker run --network test-network \
          -v ${{ github.workspace }}/postman-collection:/etc/newman \
          -v ${{ github.workspace }}/results:/etc/newman/results \
          -t postman/newman \
          run /etc/newman/Testing.postman_collection.json \
          --reporter-json-export /etc/newman/results/g1gc_results.json

      # Stop and remove the G1GC container
      - name: Stop and Remove G1GC Container
        run: |
          docker compose down --remove-orphans
          docker rm -f $(docker ps -aq)

      # Build and start the ZGC container
      - name: Run ZGC Container
        run: |
          docker compose up -d gc-testing-app-zgc

      # Wait for the application to start
      - name: Wait for Application Start
        run: sleep 10

      # Run Postman tests for ZGC
      - name: Run Postman Tests (ZGC)
        run: |
          docker run --network test-network \
          -v ${{ github.workspace }}/postman-collection:/etc/newman \
          -v ${{ github.workspace }}/results:/etc/newman/results \
          -t postman/newman \
          run /etc/newman/TestingZgc.postman_collection.json \
          --reporter-json-export /etc/newman/results/zgc_results.json

      # Stop and remove the ZGC container
      - name: Stop and Remove ZGC Container
        run: docker compose down --remove-orphans

      # Debug: List Results Directory
      - name: List Results Directory
        run: ls -la results

      # Publish Test Results for G1GC
      - name: Publish G1GC Test Results
        uses: actions/upload-artifact@v3
        with:
          name: g1gc_results
          path: results/g1gc_results.json

      # Publish Test Results for ZGC
      - name: Publish ZGC Test Results
        uses: actions/upload-artifact@v3
        with:
          name: zgc_results
          path: results/zgc_results.json
